cordetfw_editor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('editor/', include('editor.urls')),
    path('pnpAdmin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('', TemplateView.as_view(template_name='index_top.html')),
]

editor/urls.py
from django.urls import include, path
from django.contrib.auth import views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('help/', views.help, name='help'),
    path('repair/', views.repair, name='repair'),
    path('', include('django.contrib.auth.urls')),
    path('change_password', views.change_password, name='change_password'),
    
    path('add_project', views.add_project, name='add_project'),
    path('<int:project_id>/edit_project', views.edit_project, name='edit_project'),
    path('<int:project_id>/del_project', views.del_project, name='del_project'),
    path('<int:project_id>/export_project', views.export_project, name='export_project'),
    path('import_project', views.import_project, name='import_project'),
    path('<int:project_id>/make_project_release', views.make_project_release, name='make_project_release'),

    path('<int:project_id>/add_val_set', views.add_val_set, name='add_val_set'),
    path('<int:project_id>/<int:val_set_id>/edit_val_set', views.edit_val_set, name='edit_val_set'),
 
    path('<int:project_id>/add_application', views.add_application, name='add_application'),
    path('<int:application_id>/edit_application', views.edit_application, name='edit_application'),
    path('<int:application_id>/make_application_release', views.make_application_release, name='make_application_release'),

    path('<str:cat>/<int:project_id>/<int:application_id>/<int:val_set_id>/<str:sel_val>/<int:sel_rel_id>/list_spec_items', views.list_spec_items, name='list_spec_items'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:item_id>/<str:sel_val>/list_spec_item_history', views.list_spec_item_history, name='list_spec_item_history'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<str:sel_val>/<int:sel_rel_id>/add_spec_item', views.add_spec_item, name='add_spec_item'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:item_id>/<str:sel_val>/<int:sel_rel_id>/edit_spec_item', views.edit_spec_item, name='edit_spec_item'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:item_id>/<str:sel_val>/<int:sel_rel_id>/copy_spec_item', views.copy_spec_item, name='copy_spec_item'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:item_id>/<str:sel_val>/<int:sel_rel_id>/split_spec_item', views.split_spec_item, name='split_spec_item'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:item_id>/<str:sel_val>/<int:sel_rel_id>/del_spec_item', views.del_spec_item, name='del_spec_item'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:val_set_id>/<str:sel_val>/<int:sel_rel_id>/export_spec_items', views.export_spec_items, name='export_spec_items'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:val_set_id>/<str:sel_val>/import_spec_items', views.import_spec_items, name='import_spec_items'),
    path('<str:cat>/<int:project_id>/<int:application_id>/<int:item_id>/<str:sel_val>/<int:sel_rel_id>/refresh_spec_item', views.refresh_spec_item, name='refresh_spec_item'),
    
]

editor/views.py
import os
import csv
import traceback
import json

from io import StringIO
from zipfile import ZipFile 
from datetime import datetime
from tablib import Dataset
from itertools import chain
from zipfile import ZipFile
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect
from django.forms import formset_factory                                 
from django.views import generic
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash, get_user
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.core.exceptions import ObjectDoesNotExist
from django.forms.models import model_to_dict
from django.core.paginator import Paginator
from django.http import FileResponse
from django.utils.timezone import get_current_timezone
from django.db.models import OuterRef, Subquery

from editor.configs import configs
from editor.models import Project, ProjectUser, Application, Release, ValSet, SpecItem
from editor.forms import ApplicationForm, ProjectForm, ValSetForm, ReleaseForm, SpecItemForm, FindReplaceForm
from editor.utilities import get_domains, do_application_release, do_project_release, \
                             get_previous_list, spec_item_to_edit, spec_item_to_latex, \
                             spec_item_to_export, export_to_spec_item, get_expand_items, \
                             get_redirect_url, make_temp_dir, get_default_val_set_id, \
                             del_release, list_trac_items_for_latex, make_obs_spec_item_copy, \
                             mark_spec_item_aliases_as_del, create_and_init_spec_item, \
                             remove_spec_item, update_dom_name_in_val_set, remove_spec_item_aliases, \
                             get_spec_item_query
from editor.imports import import_project_tables
from editor.resources import ProjectResource, ApplicationResource, ProjectUserResource, \
                             ValSetResource, SpecItemResource, ReleaseResource
from editor.ext_cats import ext_model_refresh
from editor.access import is_project_owner, has_read_access_to_project, \
                    can_create_project, can_add_val_set, has_write_access_to_project, \
                    can_repair

import cexprtk
import logging
    
with open('/etc/dj_cordetfw_config.json') as config_file:
    config = json.load(config_file)
    
base_url = config['BASE_URL']
logger = logging.getLogger(__name__)

def index(request):
    projects = Project.objects.order_by('name').all()
    listOfProjects = []
    userRequestName = str(request.user)     
    for project in projects:
        userHasAccess = ProjectUser.objects.filter(project_id=project).\
                                        filter(user__username__contains=userRequestName).exists()
         
        applications = project.applications.all().order_by('name') 
        default_val_set_id = get_default_val_set_id(request, project)
        
        # Create iterable holding the names of the categories for this project
        project_cats = list(map(lambda x: x.strip(), project.cats.split(',')))
        # Create a subset of configs['cats'] holding only the project categories
        project_configs = {key: value for key, value in configs['cats'].items() if key in project_cats}
        
        listOfProjects.append({'project': project, 
                               'applications': list(applications),
                               'default_val_set_id': default_val_set_id,
                               'project_configs': project_configs,
                               'user_has_access': userHasAccess})
    context = {'list_of_projects': listOfProjects}
    return render(request, 'index.html', context=context)
 

def help(request):
    """Help function for home page of CordetFwEditor site"""
    context = {'project_name': 'n.a.'}
    return render(request, 'help.html', context=context)


@login_required  
def repair(request):
    """Repair database"""
    if not can_repair(request):
        return redirect(base_url)
    messages.warning(request, 'Nothing to repair')
    return redirect(base_url)


@login_required         
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below')
    else:
        form = PasswordChangeForm(request.user)


@login_required         
def add_application(request, project_id):
    project = Project.objects.get(id=project_id)
    if not is_project_owner(request, project):
        return redirect(base_url)
    
    if request.method == 'POST':    # Bind form to posted data 
        form = ApplicationForm(project, request.POST)
        if form.is_valid():
            new_application = Application(name = form.cleaned_data['name'],
                                          desc = form.cleaned_data['description'],
                                          cats = form.cleaned_data['cats'],
                                          project = project)
            do_application_release(request, new_application, "Initial release for application " \
                                   + new_application.name)
            new_application.save()
            return redirect(base_url)
    else:   
        form = ApplicationForm(project)

    context = {'form': form, 'project': project, 'title': 'Add Application to Project '+project.name, }
    return render(request, 'generic_form.html', context)    

@login_required         
def add_project(request):
    if not can_create_project(request):
        return redirect(base_url)
    
    if request.method == 'POST':    
        form = ProjectForm(None, request.POST)
        if form.is_valid():
            new_project = Project(name = form.cleaned_data['name'],
                                  desc = form.cleaned_data['description'],
                                  cats = form.cleaned_data['cats'],
                                  updated_at = datetime.now(tz=get_current_timezone()),
                                  owner = form.cleaned_data['owner'])
            new_release = Release(desc = "Initial release for project " + new_project.name,
                                  release_author = get_user(request),
                                  updated_at = datetime.now(tz=get_current_timezone()),
                                  application_version = 0,
                                  project_version = 0,
                                  previous = None)
            new_release.save()
            new_project.release = new_release
            new_project.save()
            default_val_set = ValSet(desc = 'Default ValSet',
                                     updated_at = datetime.today(),
                                     project = new_project,
                                     name = 'Default')
            default_val_set.save()
            return redirect(base_url)
    else:   
        form = ProjectForm(None)

    context = {'form': form, 'title': 'Add New Project', }
    return render(request, 'generic_form.html', context)    


@login_required         
def edit_project(request, project_id):
    if not can_create_project(request):
        return redirect(base_url)
    project = Project.objects.get(id=project_id)
    
    # Handle case where edit_project is invoked to add a new user to the project or to change its role.
    # If the new user is not yet attached to the project, it is added to it in the specified role.
    # If the specified user is already attached to the project, it is checked whether it is necessary
    # to change its role
    user_id = request.GET.get('user_id')
    user_role = request.GET.get('role')
    if user_id != None:    
        user =  ProjectUser.objects.filter(project_id=project_id, user_id=user_id)
        if not ProjectUser.objects.filter(project_id=project_id, user_id=user_id).exists():
            new_project_user = ProjectUser(updated_at = datetime.now(tz=get_current_timezone()),
                                           user = User.objects.get(id=user_id),
                                           project = project,
                                           role = user_role)
            new_project_user.save()
        else:
            user =  ProjectUser.objects.get(project_id=project_id, user_id=user_id)
            if user.role != user_role:
                user.role = user_role
                user.save()
    
    # Handle case where edit_project is invoked to delete a user from the project 
    del_user_id = request.GET.get('del_user_id')
    if del_user_id != None:     
        ProjectUser.objects.filter(id=del_user_id).delete()

    # Handle case where edit_project is invoked to delete a ValSet from the project 
    del_val_set_id = request.GET.get('del_val_set_id')
    if del_val_set_id != None:     
        try:
            ValSet.objects.filter(id=del_val_set_id).delete()    
        except Exception as e:
            messages.error(request, 'Failure to delete ValSet with id '+str(del_val_set_id)+\
                                    ', possibly because it is still in use: '+repr(e))

    if request.method == 'POST':    # Bind form to posted data 
        form = ProjectForm(project, request.POST)
        if form.is_valid():
            project.name = form.cleaned_data['name']
            project.desc = form.cleaned_data['description']
            project.owner = form.cleaned_data['owner']
            project.cats = form.cleaned_data['cats']

editor/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

        <link href="/static/bootstrap-suggest.css" rel="stylesheet">
    </head>
    <body class="d-flex flex-column min-vh-100">

        <header class="container-fluid px-md-4">
            <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-3 border-bottom">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        {% url 'index' as index_url %}
                        <a class="nav-link {% if request.get_full_path == index_url %} active {% endif %}" href="{{ index_url }}">Home</a>
                    </li>
                    <li class="nav-item">
                        {% url 'admin:index' as admin_url %}
                        <a class="nav-link {% if request.get_full_path == admin_url %} active {% endif %}" href="{{ admin_url }}">Admin</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        {% url 'repair' as repair_url %}
                        <a class="nav-link {% if request.get_full_path == repair_url %} active {% endif %}" href="{{ repair_url }}">Repair</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        {% url 'help' as help_url %}
                        <a class="nav-link {% if request.get_full_path == help_url %} active {% endif %}" href="{{ help_url }}">Help</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                <div aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0">
                        {% if project.name|length > 0 %}
                        <li class="breadcrumb-item">
                            <a href="{% url 'index' %}">
                                Cordet FW Editor: Projects
                            </a>
                        </li>
                        <li class="breadcrumb-item dropdown me-3" aria-current="page">
                            <div class="dropdown-toggle" id="catAllDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ project.name }}
                            </div>
                            <ul class="dropdown-menu" aria-labelledby="catAllDropdown">
                                {% for cat_item in breadcrumb.rest %}
                                <li><a class="dropdown-item"
                                       href="{% url 'list_spec_items' cat_item.spec_item cat_item.project_id cat_item.application_id cat_item.val_set_id cat_item.domain_id sel_rel_id%}?disp={{disp}}">
                                    {{ cat_item.list_as }}
                                </a> </li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% if application_id > 0 %}
                        <li class="breadcrumb-item">
                            {{ breadcrumb.application_name_active }}
                        </li>
                        {% endif %}
                        {% if config.name|length > 0 %}
                        <li class="breadcrumb-item active dropdown" aria-current="page">
                            <div class="dropdown-toggle" id="catDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ config.name }}
                            </div>
                            <ul class="dropdown-menu" aria-labelledby="catDropdown">
                                {% for cat_item in breadcrumb.active %}
                                <li><a class="dropdown-item"
                                       href="{% url 'list_spec_items' cat_item.spec_item cat_item.project_id cat_item.application_id cat_item.val_set_id cat_item.domain_id sel_rel_id%}?disp={{disp}}">
                                    {{ cat_item.list_as }}
                                </a> </li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% elif title|length > 0 %}
                        <li class="breadcrumb-item active" aria-current="page">
                            {{ title }}
                        </li>
                        {% endif %}
                        {% else %}
                        <li class="breadcrumb-item active" aria-current="page">
                            Cordet FW Editor: Projects
                        </li>
                        {% endif %}
                    </ol>
                </div>
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link disabled">
                            {{ user.get_username }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">
                            Logout
                        </a>
                    </li>
                </ul>
                {% endif %}
            </nav>
        </header>

        <main class="flex-grow-1">
            {% if messages %}
            <div class="container">
                {% for message in messages %}
                <div class="alert alert-dismissible fade show
                            {% if message.level <= 20 %}  <!-- debug & info -->
                            alert-info
                            {% elif message.level == 25 %}  <!-- success -->
                            alert-success
                            {% elif message.level == 30 %}
                            alert-warning
                            {% elif message.level == 40 %}
                            alert-danger
                            {% endif %}
                            " role="alert">
                    {{ message }}
                    <button type="button" class="btn-close"
                            data-bs-dismiss="alert" aria-label="Close">
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {% block content %}{% endblock %}
        </main>

        <div class="container-fluid px-md-4">
            <footer class="py-3 my-4 border-top">
                <p class="text-center text-muted">© 2022 
                    <a class="link-primary text-decoration-none"
                       href="https://www.pnp-software.com"
                       target="_blank" >P&P Software GmbH</a>. All Rights Reserved.
                </p>
            </footer>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>

editor/templates/edit_project.html
{% extends "base_generic.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-xl-9">
            <h2 class="my-3">Add or Edit a Project</h2>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                {% include "generic_form_field.html" %}
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
            {% endif %}


            <div class="row mt-5">
                <!-- user table -->
                <div class="col-12 col-md-6">
                    <div class="d-flex mb-2">
                        <div class="dropdown me-2">
                            <button class="btn btn-outline-secondary dropdown-toggle"
                                    type="button"
                                    id="dropdownAddRWUser" data-bs-toggle="dropdown">
                                Add R/W User
                            </button>
                            <ul class="dropdown-menu"
                                aria-labelledby="dropdownAddRWUser">
                                {% for user in users %}
                                <li><a class="dropdown-item"
                                       href="{% url 'edit_project' project.id %}?user_id={{user.id}}&role=RW">
                                    {{user.username}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="dropdown">
                            <button class="btn btn-outline-secondary dropdown-toggle"
                                    type="button"
                                    id="dropdownAddROUser" data-bs-toggle="dropdown">
                                Add R/O User
                            </button>
                            <ul class="dropdown-menu"
                                aria-labelledby="dropdownAddROUser">
                                {% for user in users %}
                                <li><a class="dropdown-item"
                                       href="{% url 'edit_project' project.id %}?user_id={{user.id}}&role=RO">
                                    {{user.username}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr class="table-primary">
                                <th>User Name</th>
                                <th>Last Name</th>
                                <th>First Name</th>
                                <th>Role</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project_user in project_users %}
                            <tr>
                                <td>{{ project_user.user.username }}</td>
                                <td>{{ project_user.user.last_name }}</td>
                                <td>{{ project_user.user.first_name }}</td>
                                <td>{{ project_user.role }}</td>
                                <td>
                                    <a class="bi-trash-fill link-danger text-decoration-none"
                                       role="button"
                                       href="{% url 'edit_project' project.id %}?del_user_id={{project_user.id}}"
                                       onclick="return confirm('Are you sure you want to remove this user from the project?');"
                                       title="Delete Project User">
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- ValSet table -->
                <div class="col-12 col-md-6">
                    <a class="btn btn-outline-secondary mb-2"
                       href="{% url 'add_val_set' project.id %}">
                        Add ValSet
                    </a>
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr class="table-primary">
                                <th>Name</th>
                                <th>Description</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for val_set in val_sets %}
                            <tr>
                                <td>{{ val_set.name }}</td>
                                <td>{{ val_set.desc }}</td>
                                <td>
                                    <nobr class="float-end">
                                        {% if val_set.name == 'Default' %}
                                        <span class="bi-trash-fill link-secondary me-1"
                                              aria-disabled="true">
                                        </span>
                                        <span class="bi-pencil-fill link-secondary"
                                              aria-disabled="true">
                                        </span>
                                        {% else %}
                                        <a class="bi-trash-fill link-danger text-decoration-none me-1"
                                           href="{% url 'edit_project' project.id %}?del_val_set_id={{val_set.id}}"
                                           title="Delete ValSet">
                                        </a>
                                        <a class="bi-pencil-fill text-decoration-none"
                                           href="{% url 'edit_val_set' project.id val_set.id %}"
                                           title="Edit ValSet">
                                        </a>
                                        {% endif %}
                                    </nobr>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

editor/templates/generic_form.html
{% extends "base_generic.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-xl-9">
            <h2 class="my-3">{{ title }}</h2>
            <p class="mb-4 fs-5 fst-italic">{{ sub_title }}</p>

            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                {% include "generic_form_field.html" %}
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

            {% include "link_suggest.html" %}

            {% if form.errors %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

editor/templates/index_top.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>P&P Software</title>
    </head>
    <body class="d-flex flex-column min-vh-100">
        <main class="flex-grow-1">
            <div class="container col-xl-10 col-xxl-8 py-5">
                <div class="row align-items-center g-lg-5 py-5 my-5">
                    <div class="w-50 text-center text-lg-start px-5">
                        <h1 class="fs-5 display-4 fw-bold lh-1 mb-3 text-center">P&P Software</h1>
                        <p class="fs-6 text-center">We offer consulting and engineering services. Find out more
                            <a class="font-bold
                                      hover:text-blue-600 hover:no-underline
                                      focus:text-blue-600 focus:outline-none"
                               href="https://www.pnp-software.com"
                               target="_blank" >here</a>.
                        </p>
                    </div>
                    <div class="w-50 text-center text-lg-start border-start border-2 px-5">
                        <h1 class="fs-5 display-4 fw-bold lh-1 mb-3 mt-5 text-center">Cordet FW Editor</h1>
                        <p class="fs-6 text-center mb-5">Web-based editor to support the specification of a set of related service-based applications. Find out more
                            <a class="font-bold
                                      hover:text-blue-600 hover:no-underline
                                      focus:text-blue-600 focus:outline-none"
                               href="https://www.pnp-software.com/cordetfw"
                               target="_blank" >here</a>.
                        </p>
                    </div>
                </div>
            </div>
        </main>

        <div class="container">
            <footer class="py-3 my-4 border-top">
                <p class="text-center text-muted">© 2022 
                    <a class="link-primary text-decoration-none"
                       href="https://www.pnp-software.com"
                       target="_blank" >P&P Software GmbH</a>. All Rights Reserved.
                </p>
            </footer>
        </div>

    </body>
</html>

editor/templates/lockout.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Account Locked</h1>
        <p class="col-lg-9 fs-4">Too many failed login attempts. Please try again later.</p>
    </div>
</div>
{% endblock %}